//LOGIN
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

//THEME
export const SWITCH_THEME = "SWITCH_THEME";

//COURSES
export const CREATE_NEW_COURSE = "CREATE_NEW_COURSE";
export const COURSE_LOADING = "COURSE_LOADING";
export const COURSE_ERROR = "COURSE_ERROR";
export const GET_CURRENT_USER_COURSES_AS_INSTRUCTOR =
  "GET_CURRENT_USER_COURSES_AS_INSTRUCTOR";
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";
export const CREATE_NEW_COURSE_SECTION = "CREATE_NEW_COURSE_SECTION";
export const GET_CURRENT_SECTION = "GET_CURRENT_SECTION";
export const SELECT_ACTIVITY = "SELECT_ACTIVITY";
export const SET_COURSE_EDIT_MODE = "COURSE_EDIT_MODE";
export const STUDENT_ACTIVITIES_SUCCESS = "STUDENT_ACTIVITIES_SUCCESS";
export const STUDENT_ACTIVITIES_LOADING = "STUDENT_ACTIVITIES_LOADING";
export const STUDENT_ACTIVITIES_ERROR = "STUDENT_ACTIVITIES_ERROR";

//MODAL AND MODES
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const TOGGLE_MAIN_MODAL = "TOGGLE_MAIN_MODAL";

//SIDEBAR
export const TOGGLE_SIDE_RIGHT = "TOGGLE_SIDE_RIGHT";

//FEEDS
export const CREATE_NEW_FEED = "CREATE_NEW_FEED";
export const GET_ALL_FEEDS = "GET_ALL_FEEDS";
export const FEEDS_LOADING = "FEEDS_LOADING";
export const FEEDS_ERROR = "FEEDS_ERROR";
export const SELECT_FEED = "SELECT_FEED";

//PUBLIC ROUTES
export const PUBLIC_ROUTE_LOADING = "PUBLIC_ROUTE_LOADING";
export const GET_COURSE_PUBLIC_DETAILS = "GET_COURSE_PUBLIC_DETAILS";
export const PUBLIC_ROUTE_ERROR = "PUBLIC_ROUTE_ERROR";
