//LOGIN
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//THEME
export const SWITCH_THEME = "SWITCH_THEME";

//COURSES
export const CREATE_NEW_COURSE = "CREATE_NEW_COURSE";
export const COURSE_LOADING = "COURSE_LOADING";
export const COURSE_ERROR = "COURSE_ERROR";
export const GET_CURRENT_USER_COURSES_AS_INSTRUCTOR =
  "GET_CURRENT_USER_COURSES_AS_INSTRUCTOR";
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";
export const CREATE_NEW_COURSE_SECTION = "CREATE_NEW_COURSE_SECTION";
export const GET_CURRENT_SECTION = "GET_CURRENT_SECTION";
export const SELECT_ACTIVITY = "SELECT_ACTIVITY";


//MODAL
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
